# Basics
title: Cameron Smith
description: artist
# baseurl: portfolio
url: smith.cam
email: camoverride@gmail.com

highlighter: rouge
markdown: kramdown


# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/


# Social media links in footer
github: "camoverride"
instagram: "camoverride"

highlighter: rouge
markdown: kramdown


# Optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: []


# Collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
